config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)
 
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end
 
  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
  
    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
 
    def people_params
      params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_form.html.erb
<%= form_for @person do |f| %>
  <p><%= f.label :first_name %></p>
  <p><%= f.text_field :first_name %></p>

  <p><%= f.label :last_name %></p>
  <p><%= f.text_field :last_name %></p>

  <p><%= f.label :age %></p>
  <p><%= f.number_field :age %></p>

  <p><%= f.label :hair_color %></p>
  <p><%= f.text_field :hair_color %></p>

  <p><%= f.label :eye_color %></p>
  <p><%= f.text_field :eye_color %></p>

  <p><%= f.label :gender %></p>
  <p><%= f.text_field :gender %></p>

  <p><%= f.label :alive %></p>
  <p><%= f.check_box :alive%></p>

  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
  <%= render 'layouts/form' %>

app/views/people/index.html.erb
<h1> People </h1>
<p><%= link_to 'New Person', new_person_path %></p>
<div id="cont">
<% @people.each do |person| %>
<div id="inside">
  <h2><%= person.full_name %></h2>
  <p><%= link_to 'More...', person_path(person) %></p>
  <p><%= link_to 'Edit', edit_person_path(person) %></p>
  <p><%= link_to 'Delete', person, method: :delete %></p>
</div>
<% end %>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>
  <%= render 'layouts/form' %>

app/views/people/show.html.erb
<h1>Name: <%= @person.full_name %></h1>
<p>Age: <%= @person.age %></p>
<p>Hair Color: <%= @person.hair_color %></p>
<p>Eye Color: <%= @person.eye_color %></p>
<p>Gender: <%= @person.gender %></p>
<p>Are They Alive? <%= @person.alive %></p>

<%= link_to 'Back', people_path %>